apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: cartservice:1.0.0-SNAPSHOT
          env:
          - name: dubbo.registry.address
            value: "nacos://nacos:8848"