#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  annotations:
#    nginx.ingress.kubernetes.io/service-weight: 'nacos-server: 100'
#  creationTimestamp: "2020-06-28T23:27:20Z"
#  generation: 2
#  name: nacos-ingress
#  namespace: default
#  resourceVersion: "866915526"
#  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nacos-ingress
#spec:
#  rules:
#  - http:
#      paths:
#      - backend:
#          serviceName: nacos-server
#          servicePort: 8848
#        path: /
#status:
#  loadBalancer:
#    ingress:
#    - ip: {{ .Values.slb.nacos}}