# 镜像地址的前缀
registry: registry.cn-hangzhou.aliyuncs.com/mse-demo-hz/

images:
  version: 2.0.1

mse:
  namespace: mse-demo

nacos:
  # Nacos地址
  host: nacos-server
  # 注册到Nacos的命名空间id
  namespace: public

autoscaling: false

resources:
  enable: true
  request:
    cpu: 0.75
    memory: 1.5Gi
  limit:
    cpu: 0.75
    memory: 1.5Gi