apiVersion: v1
kind: Service
metadata:
  name: sc-a
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-1
      port: 20001
      protocol: TCP
      targetPort: 20001
  selector:
    app: spring-cloud-a
  type: ClusterIP
