apiVersion: v1
kind: Service
metadata:
  name: sc-c
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-1
      port: 20003
      protocol: TCP
      targetPort: 20003
  selector:
    app: spring-cloud-c
  type: ClusterIP
