apiVersion: v1
kind: Service
metadata:
  name: go-b-service
  namespace: default
spec:
  ports:
    - name: port-1
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: b-server
  type: ClusterIP